### ISSUE TITLE
declaration.txt.attack not working

### ISSUE THREAD

**Issue by EthanTu2** [mikeizbicki/docsum#1]
I think I have finished the homework but I noticed in my tests.yml testing that the declaration.txt.attack doesn't "attack" correctly anymore and just outputs a summary of the text. Is this because we are summarizing the documents in chunks now and the program is more resistant to prompt injections or have I done something wrong?

**Comment by mikeizbicki** [comment]
I've reposted this question at https://github.com/mikeizbicki/cmc-csci181-languages/issues/11.  In general, all questions should go into the main class repo.  Everyone is following that repo, and so everyone can see the question/answer there; but no one is following this repo and so they won't see the discussion here.
